############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "/about"
weight = 2

[[main]]
name = "News"
url = "/elements"
weight = 3

[[main]]
name = "Publications"
url = "/elements"
weight = 4

[[main]]
weight = 5
name = "Projects"

[[main]]
parent = "Projects"
name = "Blog"
url = "/blog"

[[main]]
parent = "Projects"
name = "Contact"
url = "/contact"

[[main]]
parent = "Projects"
name = "Authors"
url = "/authors"

[[main]]
parent = "Projects"
name = "Categories"
url = "/categories"

[[main]]
parent = "Projects"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
