############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "/team"
weight = 2

[[main]]
name = "News"
url = "/news"
weight = 3

[[main]]
name = "Publications"
url = "/elements"
weight = 4

[[main]]
weight = 5
name = "Projects"

[[main]]
parent = "Projects"
name = "Projects1"
url = "/projects"

[[main]]
parent = "Projects"
name = "Contact"
url = "/contact"

[[main]]
parent = "Projects"
name = "team"
url = "/team"

[[main]]
parent = "Projects"
name = "Categories"
url = "/categories"

[[main]]
parent = "Projects"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
